In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('EMS_Incident_Dispatch_Data.csv')

/Users/kate/opt/anaconda3/envs/metis/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (21) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [7]:
df.head()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
0,110010790,01/01/2011 02:19:47 AM,UNC,2.0,UNC,2.0,01/01/2011 02:21:14 AM,Y,87.0,01/01/2011 02:21:31 AM,...,10030.0,32.0,9.0,110.0,5.0,13.0,N,N,N,N
1,110010791,01/01/2011 02:19:49 AM,EDP,7.0,EDP,7.0,NaN,N,0.0,NaN,...,10029.0,25.0,8.0,111.0,4.0,13.0,N,N,N,N
2,110010792,01/01/2011 02:19:52 AM,UNKNOW,3.0,UNKNOW,3.0,01/01/2011 02:25:05 AM,Y,313.0,01/01/2011 02:25:10 AM,...,10016.0,14.0,4.0,105.0,2.0,12.0,N,N,N,N
3,110010793,01/01/2011 02:19:56 AM,UNC,2.0,UNC,2.0,01/01/2011 02:20:31 AM,Y,35.0,01/01/2011 02:20:37 AM,...,11213.0,77.0,36.0,308.0,17.0,9.0,N,N,N,N
4,110010794,01/01/2011 02:20:05 AM,INJURY,5.0,INJURY,5.0,01/01/2011 03:29:04 AM,Y,4139.0,01/01/2011 03:29:04 AM,...,10022.0,18.0,4.0,105.0,2.0,12.0,N,N,N,N

In [6]:
df

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
0,110010790,01/01/2011 02:19:47 AM,UNC,2.0,UNC,2.0,01/01/2011 02:21:14 AM,Y,87.0,01/01/2011 02:21:31 AM,...,10030.0,32.0,9.0,110.0,5.0,13.0,N,N,N,N
1,110010791,01/01/2011 02:19:49 AM,EDP,7.0,EDP,7.0,NaN,N,0.0,NaN,...,10029.0,25.0,8.0,111.0,4.0,13.0,N,N,N,N
2,110010792,01/01/2011 02:19:52 AM,UNKNOW,3.0,UNKNOW,3.0,01/01/2011 02:25:05 AM,Y,313.0,01/01/2011 02:25:10 AM,...,10016.0,14.0,4.0,105.0,2.0,12.0,N,N,N,N
3,110010793,01/01/2011 02:19:56 AM,UNC,2.0,UNC,2.0,01/01/2011 02:20:31 AM,Y,35.0,01/01/2011 02:20:37 AM,...,11213.0,77.0,36.0,308.0,17.0,9.0,N,N,N,N
4,110010794,01/01/2011 02:20:05 AM,INJURY,5.0,INJURY,5.0,01/01/2011 03:29:04 AM,Y,4139.0,01/01/2011 03:29:04 AM,...,10022.0,18.0,4.0,105.0,2.0,12.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7743105,162600854,09/16/2016 07:48:52 AM,UNC,2.0,UNC,2.0,09/16/2016 07:49:33 AM,true,41.0,09/16/2016 07:50:00 AM,...,10036.0,14.0,3.0,104.0,2.0,10.0,false,false,false,false
7743106,162600856,09/16/2016 07:49:32 AM,MVAINJ,4.0,MVAINJ,4.0,09/16/2016 07:49:45 AM,true,13.0,09/16/2016 07:49:52 AM,...,11413.0,105.0,31.0,413.0,29.0,5.0,false,false,false,false
7743107,162600857,09/16/2016 07:50:02 AM,SICK,6.0,SICK,6.0,09/16/2016 07:50:19 AM,true,17.0,09/16/2016 07:50:27 AM,...,11217.0,76.0,33.0,306.0,15.0,7.0,false,false,false,false
7743108,162600858,09/16/2016 07:50:32 AM,SEIZR,3.0,SEIZR,3.0,09/16/2016 07:50:56 AM,true,24.0,09/16/2016 07:51:25 AM,...,11212.0,67.0,41.0,317.0,18.0,9.0,false,false,false,false
7743109,1626008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.sort_values('INITIAL_CALL_TYPE')

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
5637544,150983159,04/08/2015 08:39:52 PM,ABDPFC,5.0,ABDPFC,5.0,04/08/2015 08:40:11 PM,true,19.0,04/08/2015 08:40:28 PM,...,10456.0,44.0,16.0,204.0,9.0,15.0,false,false,false,false
7086813,160980282,04/07/2016 02:49:04 AM,ABDPFC,5.0,ABDPFC,5.0,04/07/2016 02:49:19 AM,true,15.0,04/07/2016 02:49:27 AM,...,11213.0,77.0,36.0,308.0,17.0,9.0,false,false,false,false
5903455,151651023,06/14/2015 06:20:52 AM,ABDPFC,5.0,ABDPFC,5.0,06/14/2015 07:06:05 AM,true,2713.0,06/14/2015 07:06:34 AM,...,10457.0,44.0,15.0,204.0,9.0,15.0,false,false,false,false
7702966,162501376,09/06/2016 10:33:56 AM,ABDPFC,5.0,ABDPFC,5.0,09/06/2016 10:34:25 AM,true,29.0,09/06/2016 10:34:43 AM,...,10458.0,52.0,15.0,207.0,10.0,13.0,false,false,false,false
6768656,160162321,01/16/2016 03:15:54 PM,ABDPFC,5.0,ABDPFC,5.0,01/16/2016 03:16:11 PM,true,17.0,01/16/2016 03:16:54 PM,...,10462.0,49.0,13.0,211.0,11.0,14.0,false,false,false,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627231,111833172,07/02/2011 07:09:45 PM,VENOM,2.0,VENOM,2.0,07/02/2011 07:09:59 PM,Y,14.0,07/02/2011 07:10:04 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N
1382070,120351117,02/04/2012 09:27:13 AM,VENOM,2.0,INJMIN,7.0,02/04/2012 09:27:30 AM,Y,17.0,02/04/2012 09:27:38 AM,...,11223.0,60.0,47.0,313.0,21.0,11.0,N,N,N,N
5897516,151634488,06/12/2015 09:07:59 PM,VENOM,2.0,VENOM,2.0,06/12/2015 09:08:50 PM,true,51.0,06/12/2015 09:09:01 PM,...,10472.0,43.0,18.0,209.0,12.0,15.0,false,false,false,false
6755963,160130809,01/13/2016 08:25:20 AM,VENOM,2.0,VENOM,2.0,01/13/2016 08:25:55 AM,true,35.0,01/13/2016 08:26:08 AM,...,11234.0,63.0,46.0,318.0,22.0,8.0,false,false,false,false
7743109,1626008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
arrests = df.loc[df['FINAL_CALL_TYPE'] == 'ARREST']

In [34]:
arrest_transports = arrests.loc[arrests['INCIDENT_DISPOSITION_CODE'] == 82]

In [35]:
arrest_transports.to_csv('arrest_transports.csv')

In [7]:
pd.set_option('display.max_columns', None)

In [18]:
arrests.tail(10000)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
7044280,160870366,03/27/2016 02:30:54 AM,ARREST,1.0,ARREST,1.0,03/27/2016 02:31:12 AM,true,18.0,03/27/2016 02:31:24 AM,03/27/2016 02:34:19 AM,true,205.0,187.0,NaN,NaN,03/27/2016 03:18:37 AM,false,83.0,QUEENS,Q5,11432.0,107.0,24.0,408.0,29.0,5.0,false,false,false,false
7044370,160870462,03/27/2016 03:21:10 AM,ARREST,1.0,ARREST,1.0,03/27/2016 03:21:37 AM,true,27.0,03/27/2016 03:21:45 AM,03/27/2016 03:27:28 AM,true,378.0,351.0,03/27/2016 03:49:02 AM,03/27/2016 03:58:53 AM,03/27/2016 04:40:43 AM,false,82.0,QUEENS,Q1,11691.0,101.0,31.0,414.0,27.0,5.0,false,false,false,false
7044544,160870647,03/27/2016 04:47:07 AM,ARREST,1.0,ARREST,1.0,03/27/2016 04:47:28 AM,true,21.0,03/27/2016 04:47:36 AM,03/27/2016 04:52:10 AM,true,303.0,282.0,03/27/2016 05:15:57 AM,03/27/2016 05:24:19 AM,03/27/2016 06:06:07 AM,false,82.0,QUEENS,Q5,11435.0,107.0,24.0,408.0,28.0,6.0,false,false,false,false
7044557,160870660,03/27/2016 04:57:18 AM,ARREST,1.0,ARREST,1.0,03/27/2016 04:57:40 AM,true,22.0,03/27/2016 04:57:49 AM,03/27/2016 04:59:49 AM,true,151.0,129.0,03/27/2016 05:44:00 AM,03/27/2016 05:49:19 AM,03/27/2016 06:25:49 AM,false,82.0,MANHATTAN,M1,10002.0,7.0,1.0,103.0,1.0,7.0,false,false,false,false
7044636,160870745,03/27/2016 05:44:01 AM,ARREST,1.0,ARREST,1.0,03/27/2016 05:44:50 AM,true,49.0,03/27/2016 05:44:56 AM,03/27/2016 05:49:59 AM,true,358.0,309.0,NaN,NaN,03/27/2016 06:58:51 AM,false,83.0,BROOKLYN,K4,11236.0,69.0,42.0,318.0,18.0,8.0,false,false,false,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7742749,162600452,09/16/2016 03:45:05 AM,ARREST,1.0,ARREST,1.0,09/16/2016 03:45:33 AM,true,28.0,09/16/2016 03:45:49 AM,09/16/2016 03:48:09 AM,true,184.0,156.0,NaN,NaN,09/16/2016 04:11:53 AM,false,90.0,MANHATTAN,M2,10014.0,6.0,3.0,102.0,2.0,10.0,false,false,false,false
7742955,162600690,09/16/2016 06:31:42 AM,ARREST,1.0,ARREST,1.0,09/16/2016 06:31:55 AM,true,13.0,09/16/2016 06:32:49 AM,09/16/2016 06:36:12 AM,true,270.0,257.0,NaN,NaN,09/16/2016 07:41:16 AM,false,83.0,BRONX,B4,10469.0,49.0,13.0,211.0,11.0,14.0,false,false,false,false
7742969,162600705,09/16/2016 06:37:59 AM,ARREST,1.0,ARREST,1.0,09/16/2016 06:38:17 AM,true,18.0,09/16/2016 06:38:27 AM,09/16/2016 06:44:27 AM,true,388.0,370.0,NaN,NaN,09/16/2016 07:02:38 AM,false,93.0,RICHMOND / STATEN ISLAND,S1,10301.0,120.0,49.0,501.0,31.0,11.0,false,false,false,false
7743006,162600748,09/16/2016 06:55:58 AM,ARREST,1.0,ARREST,1.0,09/16/2016 06:56:18 AM,true,20.0,09/16/2016 06:56:38 AM,09/16/2016 06:59:40 AM,true,222.0,202.0,09/16/2016 07:19:22 AM,09/16/2016 07:26:57 AM,09/16/2016 08:13:29 AM,false,82.0,RICHMOND / STATEN ISLAND,S1,10304.0,120.0,49.0,501.0,31.0,11.0,false,false,false,false
7743040,162600783,09/16/2016 07:13:46 AM,ARREST,1.0,ARREST,1.0,09/16/2016 07:14:12 AM,true,26.0,09/16/2016 07:14:40 AM,09/16/2016 07:18:13 AM,true,267.0,241.0,NaN,NaN,09/16/2016 08:14:38 AM,false,83.0,BRONX,B2,10468.0,46.0,14.0,205.0,10.0,15.0,false,false,false,false

In [20]:
arrests.tail(10000).to_csv('arrests.csv')

In [10]:
deaths = df.loc[df['INCIDENT_DISPOSITION_CODE'] == 83]

In [11]:
deaths

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
920,110011793,01/01/2011 05:07:06 AM,DIFFBR,2.0,DIFFBR,2.0,01/01/2011 05:07:19 AM,Y,13.0,01/01/2011 05:07:52 AM,01/01/2011 05:12:48 AM,Y,342.0,329.0,NaN,NaN,01/01/2011 06:02:03 AM,N,83.0,BROOKLYN,K5,11205.0,79.0,36.0,303.0,13.0,8.0,N,N,N,N
1146,110012045,01/01/2011 06:06:03 AM,ARREST,1.0,ARREST,1.0,01/01/2011 06:06:41 AM,Y,38.0,01/01/2011 06:06:50 AM,01/01/2011 06:10:59 AM,Y,296.0,258.0,NaN,NaN,01/01/2011 07:28:36 AM,N,83.0,BROOKLYN,K2,11220.0,72.0,38.0,307.0,20.0,7.0,N,N,N,N
1159,110012062,01/01/2011 06:09:07 AM,UNC,2.0,ARREST,1.0,01/01/2011 06:09:21 AM,Y,14.0,01/01/2011 06:09:28 AM,01/01/2011 06:14:41 AM,Y,334.0,320.0,NaN,NaN,01/01/2011 07:38:42 AM,N,83.0,MANHATTAN,M8,10037.0,25.0,9.0,111.0,5.0,13.0,N,N,N,N
1266,110012184,01/01/2011 06:42:51 AM,ARREST,1.0,ARREST,1.0,01/01/2011 06:43:30 AM,Y,39.0,01/01/2011 06:43:44 AM,01/01/2011 06:50:07 AM,Y,436.0,397.0,NaN,NaN,01/01/2011 07:32:09 AM,N,83.0,QUEENS,Q6,11377.0,108.0,26.0,402.0,30.0,14.0,N,N,N,N
1281,110012202,01/01/2011 06:49:05 AM,ARREST,1.0,ARREST,1.0,01/01/2011 06:49:47 AM,Y,42.0,01/01/2011 06:49:56 AM,01/01/2011 06:50:03 AM,Y,58.0,16.0,NaN,NaN,01/01/2011 07:21:36 AM,N,83.0,BROOKLYN,K2,11228.0,68.0,43.0,310.0,20.0,11.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7742410,162600083,09/16/2016 12:35:05 AM,ARREST,1.0,ARREST,1.0,09/16/2016 12:35:21 AM,true,16.0,09/16/2016 12:35:31 AM,09/16/2016 12:39:09 AM,true,244.0,228.0,NaN,NaN,09/16/2016 01:13:24 AM,false,83.0,BROOKLYN,K6,11215.0,78.0,39.0,306.0,15.0,9.0,false,false,false,false
7742445,162600125,09/16/2016 12:51:56 AM,ARREST,1.0,ARREST,1.0,09/16/2016 12:52:44 AM,true,48.0,09/16/2016 12:53:01 AM,09/16/2016 01:00:18 AM,true,502.0,454.0,NaN,NaN,09/16/2016 01:35:24 AM,false,83.0,RICHMOND / STATEN ISLAND,S3,10309.0,123.0,51.0,503.0,31.0,11.0,false,false,false,false
7742893,162600610,09/16/2016 05:42:00 AM,UNC,2.0,UNC,2.0,09/16/2016 05:43:14 AM,true,74.0,09/16/2016 05:43:27 AM,09/16/2016 05:51:47 AM,true,587.0,513.0,NaN,NaN,09/16/2016 06:26:54 AM,false,83.0,QUEENS,Q3,11420.0,106.0,28.0,410.0,28.0,5.0,false,false,false,false
7742955,162600690,09/16/2016 06:31:42 AM,ARREST,1.0,ARREST,1.0,09/16/2016 06:31:55 AM,true,13.0,09/16/2016 06:32:49 AM,09/16/2016 06:36:12 AM,true,270.0,257.0,NaN,NaN,09/16/2016 07:41:16 AM,false,83.0,BRONX,B4,10469.0,49.0,13.0,211.0,11.0,14.0,false,false,false,false
7743040,162600783,09/16/2016 07:13:46 AM,ARREST,1.0,ARREST,1.0,09/16/2016 07:14:12 AM,true,26.0,09/16/2016 07:14:40 AM,09/16/2016 07:18:13 AM,true,267.0,241.0,NaN,NaN,09/16/2016 08:14:38 AM,false,83.0,BRONX,B2,10468.0,46.0,14.0,205.0,10.0,15.0,false,false,false,false

In [14]:
deaths.FINAL_CALL_TYPE.unique()

array(['DIFFBR', 'ARREST', 'RESPIR', 'OTHER', 'UNC', 'CARD', 'UNKNOW',
       'INJURY', 'INBLED', 'SICK', 'STATEP', 'EDP', 'DOA', 'PEDSTR',
       'TRAUMA', 'OBLAB', 'ABDPN', 'JUMPDN', 'INHALE', 'SHOT', 'MCI21P',
       'ASTHMB', 'DROWN', 'STAB', 'CVAC', 'BURNMA', 'MCI43P', 'MVAINJ',
       'STNDBY', 'DRUG', 'CHOKE', 'ALTMEN', 'SEIZR', 'ELECT', 'INJMAJ',
       'CHILDA', 'OBOUT', 'INJMIN', 'JUMPUP', 'PD13', 'ANAPH', 'MCI80P',
       'GYNHEM', 'BURNMI', 'SICPED', 'MCI22P', 'CVA', 'SICMIN', 'SPEVNT',
       'MCI30P', 'MCI34P', 'MCI40P', 'MCI59P'], dtype=object)

In [19]:
arrest_deaths = deaths.loc[deaths['FINAL_CALL_TYPE'] == "ARREST"]

In [20]:
arrest_deaths.to_csv('arrest_deaths.csv')